import statistics
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

class AITextDetector:
    """
    Analyzes text to determine if it was likely generated by an AI.
    
    Current Implementation: Heuristic (Statistical)
    Future Implementation: HuggingFace Transformer (roberta-base-openai-detector)
    """
    
    def detect(self, text: str) -> Dict[str, Any]:
        """
        Returns a score (0-100) indicating probability of AI generation.
        """
        if not text:
            return {"score": 0, "label": "Unknown", "details": {}}

        # Heuristic 1: Sentence Length Standard Deviation (Burstiness)
        # AI models tend to be more uniform in sentence length than humans.
        sentences = [s.strip() for s in text.split('.') if len(s.split()) > 3]
        if len(sentences) < 3:
            return {"score": 0, "label": "Insufficient Data", "details": {}}
            
        sent_lengths = [len(s.split()) for s in sentences]
        std_dev = statistics.stdev(sent_lengths)
        avg_len = statistics.mean(sent_lengths)
        
        # Heuristic 2: Vocabulary Complexity (Perplexity-lite)
        # AI often uses common words. Humans use more "surprising" words.
        # (Simplified: TTR logic reused but interpreted differently)
        # Low TTR + Low StdDev = High AI Probability
        
        # Calculate AI Score
        # Low burstiness (std_dev < 5) suggests AI
        # High burstiness (std_dev > 10) suggests Human
        
        burstiness_score = 0
        if std_dev < 5:
            burstiness_score = 80 # Likely AI
        elif std_dev < 8:
            burstiness_score = 50 # Maybe
        else:
            burstiness_score = 10 # Likely Human
            
        final_score = burstiness_score
        
        label = "Human-written"
        if final_score > 70:
            label = "Likely AI-generated"
        elif final_score > 40:
            label = "Mixed / Uncertain"
            
        return {
            "score": round(final_score, 2),
            "label": label,
            "details": {
                "burstiness": round(std_dev, 2),
                "avg_sentence_length": round(avg_len, 2)
            }
        }

ai_text_detector = AITextDetector()
