"""
Gemini-Powered Essay Evaluator

Replaces weak statistical analyzers (vocabulary, coherence, topic relevance,
AI detection) with a single structured Gemini API call that returns scores,
reasoning, strengths, and improvement suggestions for each dimension.

Uses model fallback: tries gemini-2.5-flash first, falls back to gemini-2.0-flash
if rate-limited.
"""

import json
import logging
from typing import Dict, Any, Optional

from app.core.config import settings

logger = logging.getLogger(__name__)

# Ordered list of models to try (each has its own rate limit quota)
MODEL_CHAIN = [
    "gemini-2.5-flash",
    "gemini-2.0-flash",
    "gemini-2.0-flash-lite",
]

# Lazy-initialized model cache (avoids reconfiguring API key on every call)
_configured = False
_model_cache: Dict[str, Any] = {}


def _get_model(model_name: str):
    """Get or create a cached Gemini model instance."""
    global _configured
    if not _configured:
        import google.generativeai as genai
        genai.configure(api_key=settings.GEMINI_API_KEY)
        _configured = True

    if model_name not in _model_cache:
        import google.generativeai as genai
        _model_cache[model_name] = genai.GenerativeModel(
            model_name,
            generation_config={
                "response_mime_type": "application/json",
                "temperature": 0.3,
            },
        )
    return _model_cache[model_name]


EVALUATION_PROMPT = """You are an expert academic essay evaluator. Analyze the following essay and provide structured scores.

## Essay to Evaluate:
{essay_text}

{prompt_section}

## Scoring Instructions:
Evaluate the essay on each dimension below. For each, provide:
- `score`: An integer from 0-100
- `reasoning`: A 1-2 sentence explanation of WHY you gave this score
- `strengths`: A list of 1-2 specific things done well
- `improvements`: A list of 1-2 specific, actionable suggestions

### Dimensions to Score:

1. **grammar** — Evaluate overall grammatical correctness, spelling, punctuation, and sentence structure. Consider the severity and frequency of errors relative to the essay's length. Minor typos in an otherwise well-written essay should not tank the score. A score of 70+ means the writing is mostly error-free with only minor issues.

2. **vocabulary** — Evaluate lexical diversity, word choice precision, use of academic/domain vocabulary, and avoidance of repetition. A score of 70+ means the writing uses varied, precise, and appropriate vocabulary.

3. **coherence** — Evaluate logical flow between sentences and paragraphs, effective use of transitions, consistency of argument, and overall structure (intro → body → conclusion). A score of 70+ means ideas connect naturally and the essay has clear structure.

4. **topic_relevance** — Evaluate how well the essay addresses the prompt/topic. Does it stay focused? Does it cover the key aspects the prompt asks for? A score of 70+ means the essay directly and thoroughly addresses the topic. If the essay is completely off-topic (e.g., writing about cooking when asked about technology), give a score below 10.

5. **ai_detection** — Evaluate whether this text appears to be written by a human or generated by AI. Look for: personal voice, varied sentence patterns, natural imperfections, authentic examples, emotional engagement. Return a score where 0 = definitely human, 100 = definitely AI-generated. Also include a `label` field with one of: "Likely Human", "Mixed / Uncertain", "Likely AI-generated".

## Required JSON Output Format:
Return a JSON object with exactly these keys: grammar, vocabulary, coherence, topic_relevance, ai_detection.
Each key (except ai_detection) should have: score (int), reasoning (string), strengths (list of strings), improvements (list of strings).
ai_detection should have: score (int), reasoning (string), label (string).
"""


class GeminiEvaluator:
    """
    Uses Gemini to evaluate essay quality across ALL dimensions
    in a single API call with structured JSON output.
    
    Gemini handles: grammar, vocabulary, coherence, topic_relevance, ai_detection.
    LanguageTool is still used separately for error span highlighting (UI only).
    
    Tries multiple models in sequence to handle per-model rate limits.
    """

    async def evaluate(
        self, text: str, prompt: Optional[str] = None
    ) -> Optional[Dict[str, Any]]:
        """
        Evaluate essay text across all dimensions using Gemini.
        Tries each model in MODEL_CHAIN until one succeeds.
        Returns structured results or None if all models fail.
        """
        if not settings.GEMINI_API_KEY:
            logger.warning("No GEMINI_API_KEY configured.")
            return None

        # Build prompt
        if prompt:
            prompt_section = f"## Essay Prompt/Topic:\n{prompt}"
        else:
            prompt_section = (
                "## Essay Prompt/Topic:\nNo specific prompt was provided. "
                "Evaluate topic relevance based on internal coherence and focus."
            )

        # Truncate essay to ~3000 words for token efficiency
        words = text.split()
        truncated = " ".join(words[:3000])
        if len(words) > 3000:
            truncated += "\n[... essay truncated for analysis ...]"

        full_prompt = EVALUATION_PROMPT.format(
            essay_text=truncated, prompt_section=prompt_section
        )

        # Try each model in the chain
        last_error = None
        for model_name in MODEL_CHAIN:
            try:
                logger.info(f"Trying Gemini model: {model_name}")
                model = _get_model(model_name)
                response = await model.generate_content_async(full_prompt)
                raw = response.text.strip()

                # Parse JSON response
                result = json.loads(raw)

                # Validate structure
                required_keys = {"grammar", "vocabulary", "coherence", "topic_relevance", "ai_detection"}
                if not required_keys.issubset(result.keys()):
                    logger.error(f"Gemini response missing keys. Got: {result.keys()}")
                    continue  # Try next model

                # Clamp scores to 0-100
                for key in ["grammar", "vocabulary", "coherence", "topic_relevance", "ai_detection"]:
                    if "score" in result[key]:
                        result[key]["score"] = max(0, min(100, int(result[key]["score"])))

                result["_engine"] = "gemini"
                result["_model"] = model_name

                logger.info(f"Gemini evaluation completed with model: {model_name}")
                return result

            except json.JSONDecodeError as e:
                logger.error(f"Model {model_name} returned invalid JSON: {e}")
                last_error = e
                continue
            except Exception as e:
                err_str = str(e)
                if "429" in err_str or "quota" in err_str.lower():
                    logger.warning(f"Model {model_name} is rate-limited. Trying next model...")
                    last_error = e
                    continue
                else:
                    logger.error(f"Model {model_name} failed: {e}")
                    last_error = e
                    continue

        logger.error(f"All Gemini models exhausted. Last error: {last_error}")
        return None


gemini_evaluator = GeminiEvaluator()
